[package]
name = "jangal"
version = "0.0.2"
license = "MIT"
description = "Implementation of Tree Data Structures in Rust"
exclude = [
    "flake.nix",
    "flake.lock",
    ".github/",
    ".pre-commit-config.yaml",
]